const api='/api';
let productCache=[];
let currentCart=null;
const headers=()=>({'Content-Type':'application/json','X-API-KEY':localStorage.getItem('socKey')||''});
const customer=()=>{try{return JSON.parse(localStorage.getItem('socCustomer'))}catch{return null}};
function saveKey(){const key=document.querySelector('#apiKey').value.trim();if(!key){alert('Please enter an API key');return}localStorage.setItem('socKey',key);alert('API key saved successfully');loadProducts()}
function show(id){document.querySelector('#shop').classList.toggle('hidden',id!=='shop');document.querySelector('#admin').classList.toggle('hidden',id!=='admin')}
function showCart(){show('shop');document.querySelector('#cartPanel').scrollIntoView({behavior:'smooth'});loadCart()}
async function call(path,opt={}){const r=await fetch(api+path,{...opt,headers:{...headers(),...(opt.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(text||`Request failed (${r.status})`);return (r.headers.get('content-type')||'').includes('json')?JSON.parse(text):text}
async function loadProducts(){const box=document.querySelector('#products');try{productCache=await call('/products');box.innerHTML=productCache.map(p=>`<article class="product"><img src="${p.imageUrl||'https://placehold.co/600x400?text=Product'}" alt=""><div><h3>${p.name}</h3><p>${p.description}</p><p class="price">LKR ${p.price}</p><small>${p.stock} in stock</small><button ${p.stock<1?'disabled':''} onclick="addToCart('${p.id}')">${p.stock<1?'Out of stock':'Add to cart'}</button></div></article>`).join('')||'<p>No products yet.</p>'}catch(e){box.innerHTML=`<pre>${e.message}</pre>`}}
async function createCustomer(){const result=document.querySelector('#customerResult');try{const c=await call('/customers',{method:'POST',body:JSON.stringify({name:cname.value,email:cemail.value,phone:cphone.value,address:caddress.value})});localStorage.setItem('socCustomer',JSON.stringify(c));result.textContent=`Customer ready: ${c.name} (${c.id})`;renderCustomer();await loadCart()}catch(e){result.textContent=e.message}}
function renderCustomer(){const c=customer();document.querySelector('#activeCustomer').textContent=c?`Buying as ${c.name} · Delivery to ${c.address}`:'Register before adding products to your cart.'}
async function addToCart(productId){const c=customer();if(!c){alert('Please register customer details first');document.querySelector('#activeCustomer').scrollIntoView({behavior:'smooth'});return}const p=productCache.find(x=>x.id===productId);if(!p)return;try{await call(`/carts/${c.id}/items`,{method:'POST',body:JSON.stringify({productId:p.id,productName:p.name,quantity:1,unitPrice:p.price})});await loadCart();alert(`${p.name} added to cart`)}catch(e){alert(e.message)}}
async function loadCart(){const c=customer(),box=document.querySelector('#cartItems');if(!c){currentCart=null;box.innerHTML='<p>Register customer details before using the cart.</p>';updateCartSummary();return}try{currentCart=await call(`/carts/${c.id}`);box.innerHTML=currentCart.items.length?currentCart.items.map(i=>`<div class="cart-row"><strong>${i.productName}</strong><span>${i.quantity} × LKR ${i.unitPrice}</span><span>LKR ${(i.quantity*i.unitPrice).toFixed(2)}</span><button onclick="removeFromCart('${i.productId}')">Remove</button></div>`).join(''):'<p>Your cart is empty.</p>';updateCartSummary()}catch(e){box.innerHTML=`<pre>${e.message}</pre>`}}
function updateCartSummary(){const items=currentCart?.items||[];document.querySelector('#cartCount').textContent=items.reduce((n,i)=>n+i.quantity,0);document.querySelector('#cartTotal').textContent=`Total: LKR ${currentCart?.total||0}`}
async function removeFromCart(productId){const c=customer();try{currentCart=await call(`/carts/${c.id}/items/${productId}`,{method:'DELETE'});await loadCart()}catch(e){alert(e.message)}}
async function checkout(){const c=customer(),result=document.querySelector('#checkoutResult');if(!c){alert('Please register customer details first');return}if(!currentCart?.items?.length){alert('Your cart is empty');return}try{const order=await call('/orders',{method:'POST',body:JSON.stringify({customerId:c.id,customerName:c.name,address:c.address,items:currentCart.items})});await call(`/carts/${c.id}`,{method:'DELETE'});result.textContent=`Order placed successfully\nOrder: ${order.id}\nTotal: LKR ${order.total}`;await loadCart();if(confirm('Order placed. Open printable bill now?'))openBill(order.id)}catch(e){result.textContent=e.message}}
async function addProduct(){try{await call('/products',{method:'POST',body:JSON.stringify({name:pname.value,description:pdescription.value,price:+pprice.value,stock:+pstock.value,imageUrl:pimage.value})});alert('Product created');loadProducts()}catch(e){alert(e.message)}}
async function createKey(){try{keyResult.textContent=JSON.stringify(await call('/security/keys',{method:'POST',body:JSON.stringify({name:kname.value,role:krole.value})}),null,2)}catch(e){keyResult.textContent=e.message}}
async function loadOrders(){try{const os=await call('/orders');orders.innerHTML=os.map(o=>`<p><b>${o.id}</b> — ${o.customerName} — LKR ${o.total} — ${o.status} <button onclick="openBill('${o.id}')">Open bill</button></p>`).join('')}catch(e){orders.innerHTML=`<pre>${e.message}</pre>`}}
async function openBill(id){try{const html=await call('/orders/'+id+'/bill');const w=open();w.document.write(html);w.document.close()}catch(e){alert(e.message)}}
document.querySelector('#apiKey').value=localStorage.getItem('socKey')||'';
renderCustomer();
if(localStorage.getItem('socKey')){loadProducts();loadCart()}
