package com.soc.gateway;
import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.*;import org.springframework.boot.autoconfigure.*;import org.springframework.cloud.gateway.filter.*;import org.springframework.context.annotation.Bean;import org.springframework.core.*;import org.springframework.http.*;import org.springframework.web.cors.CorsConfiguration;import org.springframework.web.cors.reactive.*;import org.springframework.web.reactive.function.client.WebClient;import reactor.core.publisher.Mono;import java.util.*;
@SpringBootApplication public class ApiGatewayApplication{
 public static void main(String[]a){SpringApplication.run(ApiGatewayApplication.class,a);}
 @Bean WebClient webClient(){return WebClient.builder().build();}
 @Bean CorsWebFilter cors(@Value("${app.cors-origin}")String origin){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(List.of(origin));c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("Content-Type","X-API-KEY"));UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return new CorsWebFilter(s);}
 @Bean GlobalFilter apiKeyFilter(WebClient web,@Value("${app.security-url}")String securityUrl){return new GlobalFilter(){public Mono<Void> filter(org.springframework.web.server.ServerWebExchange ex,GatewayFilterChain chain){if(ex.getRequest().getMethod()==HttpMethod.OPTIONS||ex.getRequest().getPath().value().startsWith("/actuator"))return chain.filter(ex);String key=ex.getRequest().getHeaders().getFirst("X-API-KEY");if(key==null)return deny(ex,"Missing X-API-KEY");return web.post().uri(securityUrl+"/security/validate").header("X-API-KEY",key).retrieve().bodyToMono(Validation.class).flatMap(v->{if(!v.valid())return deny(ex,"Invalid API key");String path=ex.getRequest().getPath().value();boolean adminOnly=path.startsWith("/api/security/")&&!path.endsWith("/validate")||(path.startsWith("/api/products")&&ex.getRequest().getMethod()!=HttpMethod.GET);if(adminOnly&&!"ADMIN".equals(v.role()))return forbidden(ex);return chain.filter(ex.mutate().request(ex.getRequest().mutate().header("X-CLIENT-ROLE",v.role()==null?"":v.role()).build()).build());}).onErrorResume(e->deny(ex,"Security service unavailable"));}public int getOrder(){return Ordered.HIGHEST_PRECEDENCE;} };}
 private static Mono<Void> deny(org.springframework.web.server.ServerWebExchange ex,String message){ex.getResponse().setStatusCode(HttpStatus.UNAUTHORIZED);ex.getResponse().getHeaders().setContentType(MediaType.APPLICATION_JSON);return ex.getResponse().writeWith(Mono.just(ex.getResponse().bufferFactory().wrap(("{\"error\":\""+message+"\"}").getBytes())));}
 private static Mono<Void> forbidden(org.springframework.web.server.ServerWebExchange ex){ex.getResponse().setStatusCode(HttpStatus.FORBIDDEN);return ex.getResponse().setComplete();}
 record Validation(boolean valid,String role){}
}
