package com.soc.order;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.*;import org.springframework.boot.autoconfigure.*;import org.springframework.data.annotation.Id;import org.springframework.data.mongodb.core.mapping.Document;import org.springframework.data.mongodb.repository.MongoRepository;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.RestClient;import org.springframework.web.client.RestClientResponseException;import java.math.*;import java.time.*;import java.util.*;
@SpringBootApplication public class OrderServiceApplication{public static void main(String[]a){SpringApplication.run(OrderServiceApplication.class,a);}}
record OrderItem(@NotBlank String productId,@NotBlank String productName,@Min(1) int quantity,@NotNull @Positive BigDecimal unitPrice){}
@Document("orders") record Order(@Id String id,@NotBlank String customerId,@NotBlank String customerName,@NotBlank String address,List<@Valid OrderItem> items,BigDecimal subtotal,BigDecimal tax,BigDecimal total,String status,Instant createdAt){}
interface OrderRepository extends MongoRepository<Order,String>{List<Order> findByCustomerId(String id);}
record ProductStock(String id,String name,String description,BigDecimal price,int stock,String imageUrl,boolean active){}
@RestController @RequestMapping("/orders") class OrderController{
 private final OrderRepository repo;private final RestClient products;OrderController(OrderRepository r,@Value("${app.product-url:http://localhost:8081}")String productUrl){repo=r;products=RestClient.builder().baseUrl(productUrl).build();}
 @GetMapping List<Order> all(){return repo.findAll();}
 @GetMapping("/{id}") Order one(@PathVariable String id){return repo.findById(id).orElseThrow(()->new NoSuchElementException("Order not found"));}
 @GetMapping("/customer/{id}") List<Order> customer(@PathVariable String id){return repo.findByCustomerId(id);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) Order create(@Valid @RequestBody Order o){if(o.items()==null||o.items().isEmpty())throw new IllegalArgumentException("Order needs at least one item");List<OrderItem> verified=new ArrayList<>();try{for(OrderItem i:o.items()){ProductStock p=products.patch().uri("/products/{id}/decrease-stock?quantity={quantity}",i.productId(),i.quantity()).retrieve().body(ProductStock.class);if(p==null)throw new IllegalArgumentException("Unable to update product stock");verified.add(new OrderItem(p.id(),p.name(),i.quantity(),p.price()));}}catch(RestClientResponseException e){throw new IllegalArgumentException("Purchase failed: product is unavailable or stock is insufficient");}BigDecimal sub=verified.stream().map(i->i.unitPrice().multiply(BigDecimal.valueOf(i.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal tax=sub.multiply(new BigDecimal("0.08")).setScale(2,RoundingMode.HALF_UP);return repo.save(new Order(null,o.customerId(),o.customerName(),o.address(),verified,sub,tax,sub.add(tax),"PLACED",Instant.now()));}
 @PatchMapping("/{id}/status") Order status(@PathVariable String id,@RequestParam String value){Order o=one(id);return repo.save(new Order(o.id(),o.customerId(),o.customerName(),o.address(),o.items(),o.subtotal(),o.tax(),o.total(),value.toUpperCase(),o.createdAt()));}
 @GetMapping(value="/{id}/bill",produces=MediaType.TEXT_HTML_VALUE) String bill(@PathVariable String id){Order o=one(id);StringBuilder rows=new StringBuilder();o.items().forEach(i->rows.append("<tr><td>").append(esc(i.productName())).append("</td><td>").append(i.quantity()).append("</td><td>").append(i.unitPrice()).append("</td></tr>"));return "<!doctype html><html><head><title>Bill "+o.id()+"</title><style>body{font-family:Arial;max-width:700px;margin:40px auto}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd}.total{text-align:right}button{padding:10px}</style></head><body><h1>SOC Shop Invoice</h1><p>Bill #"+o.id()+"<br>Customer: "+esc(o.customerName())+"<br>Date: "+o.createdAt()+"</p><table><tr><th>Item</th><th>Qty</th><th>Price</th></tr>"+rows+"</table><div class='total'><p>Subtotal: LKR "+o.subtotal()+"</p><p>Tax: LKR "+o.tax()+"</p><h2>Total: LKR "+o.total()+"</h2></div><button onclick='print()'>Print / Save PDF</button></body></html>";}
 private String esc(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
 @ExceptionHandler({NoSuchElementException.class,IllegalArgumentException.class}) ResponseEntity<Map<String,String>> error(RuntimeException e){return ResponseEntity.status(e instanceof NoSuchElementException?404:400).body(Map.of("error",e.getMessage()));}
}